image:
  - Visual Studio 2019
  - Ubuntu
  - macOS
shallow_clone: true
branches:
  except:
    - /dev/
    - gh-pages
before_build:
  - cmd: cmake -H. -B./build -DCMAKE_PREFIX_PATH=C:\Qt\6.0.1\msvc2019_64
build:
  verbosity: normal